# This is a basic workflow to help you get started with Actions

name: Auto-generate documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: zephyr
      
      - uses: actions/checkout@v2
        with:
          repository: golioth/docs
          path: golioth-docs
      
      - name: Doxygen Action
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@9964e41e7f2e2a56e42fe789421f3fe33e938d63
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          doxyfile-path: zephyr/Doxyfile
          working-directory: .
        
      - name: Download and Run Doxybook2
        run: |
          wget -O doxybook2.zip https://github.com/matusnovak/doxybook2/releases/download/v1.3.4/doxybook2-linux-amd64-v1.3.4.zip
          unzip doxybook2.zip -d doxybook2
          doxybook2/bin/doxybook2 --input docs/xml/ --output docs/md
          
      - name: Copy generated documentation to golioth/docs
        run: |
          cp -r docs/md golioth-docs/docs/reference/docs

      - name: Create Pull Request
        # You may pin to the exact commit or the version.
        # uses: peter-evans/create-pull-request@9825ae65b1cb54b543b938503728b432a0176d29
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          # Relative path under $GITHUB_WORKSPACE to the repository. Defaults to $GITHUB_WORKSPACE.
          path: golioth-docs/ # optional
          # The message to use when committing changes.
          commit-message: Commit of autogenerated golioth/zephyr docs # optional, default is [create-pull-request] automated change
